// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSEMQhSwGv4wUt1Qczc6Z1AqE7nAnOyYI',
    appId: '1:1073569578631:web:0e3d128eb2551281be8222',
    messagingSenderId: '1073569578631',
    projectId: 'budgetbee-8711a',
    authDomain: 'budgetbee-8711a.firebaseapp.com',
    storageBucket: 'budgetbee-8711a.appspot.com',
    measurementId: 'G-HN09WN567F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcEBAcLbPK6O_thH6CV4uH6XIIkf61AMc',
    appId: '1:1073569578631:android:ec9f779cc5643c75be8222',
    messagingSenderId: '1073569578631',
    projectId: 'budgetbee-8711a',
    storageBucket: 'budgetbee-8711a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_01zgNqc_1TiOqUkGhUVvrVHVbN-MVE',
    appId: '1:1073569578631:ios:b4d1298188baeceabe8222',
    messagingSenderId: '1073569578631',
    projectId: 'budgetbee-8711a',
    storageBucket: 'budgetbee-8711a.appspot.com',
    iosClientId: '1073569578631-onh35bk7jf7jdt8qcg36gaj40ok4vka9.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetbee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd_01zgNqc_1TiOqUkGhUVvrVHVbN-MVE',
    appId: '1:1073569578631:ios:f1e09609aefdfc60be8222',
    messagingSenderId: '1073569578631',
    projectId: 'budgetbee-8711a',
    storageBucket: 'budgetbee-8711a.appspot.com',
    iosClientId: '1073569578631-9v7tn8fkdm35ruf0qhohc65qt4bqbi5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetbee.RunnerTests',
  );
}
